### ISSUE TITLE
Doesn't build executable

### ISSUE THREAD

**Issue by nooneelseexcept** [stijnherfst/HiveWE#102]
After following the instructions step by step, it still didn't build the executable for HiveWE
I used VS2022 17.11.2
![HiveWE](https://github.com/user-attachments/assets/a5ddfa82-7b62-4fd0-9349-93a0f942c310)
![Build release](https://github.com/user-attachments/assets/aa14fb52-9e73-45ff-854c-f1502f1a6a46)

I don't know if the pictures help but I attached them just in case

**Comment by nooneelseexcept** [comment]
No, there is no HiveWE.exe in any folders.
Here is the output.
[output.txt](https://github.com/user-attachments/files/16829761/output.txt)

**Comment by stijnherfst** [comment]
it's because you're building debug mode but looking in the release folder.
```1> [CMake] -- Build files have been written to: C:/HiveWE/build/debug```

**Comment by nooneelseexcept** [comment]
I build both debug and release in hopes that one or the other would build the .exe
After I build them I hit "HiveWE.exe" at the top in VS to debug it and build it. I don't know if you referencing that.
Also I wrote 
> (Debug one not Release, but same result.)
It gives me the exact same result, only that it says "Build files have been written to "release"."

**Comment by stijnherfst** [comment]
![image](https://github.com/user-attachments/assets/c3f7c27c-c010-45dd-9f81-a7fb89c833eb)
You have to press Build. If you do this do you see the .exe? And otherwise what is the output?

**Comment by nooneelseexcept** [comment]
No, I don't see the .exe
Here is the output (Sorry for the german language there)
[output build.txt](https://github.com/user-attachments/files/16830506/output.build.txt)

**Comment by stijnherfst** [comment]
Oh yeah having errors would explain it. If you just want to download a .exe then you can [try this link](https://cdn.discordapp.com/attachments/1171949129652502560/1179184868404506655/HiveWE_0.7-rc7.zip?ex=66d5913c&is=66d43fbc&hm=b0bab48fe63ae7a42812dbd75357e17f959a61ccd0fea269d1c7bf79a4b7d6f7&)

**Comment by nooneelseexcept** [comment]
Now another problem appears lol
![Error](https://github.com/user-attachments/assets/0cd74a90-5072-467d-94c8-1247566848a3)
