### ISSUE TITLE
Fatal error. 

### ISSUE THREAD

**Issue by Karaulov** [stijnherfst/HiveWE#13]
https://github.com/stijnherfst/HiveWE/blob/565db9abf80d5a74eee33c1726936826288365a9/HiveWE/Terrain.cpp#L168

**Comment by Karaulov** [comment]
After convert to 3.3 , this line cause error:

```
---------------
Debug message (1281): GL_INVALID_VALUE error generated. Texture allocation failed.
Source: API
Type: Error
Severity: high
```

**Comment by Karaulov** [comment]
Error: Texture allocation failed. (Possible "ground_textures.size( ) * 32 + 1" is big value)

**Comment by Karaulov** [comment]
I debug it, maximum 512 textures. 

if value "ground_textures.size( ) * 32 + 1" bigger than 512 - allocation crash.

**Comment by DrSuperGood** [comment]
The limitations of glTexStorage3D are described here.
https://www.khronos.org/opengl/wiki/Array_Texture

Specifically...
> Array texture sizes are normally limited to the usual GL_MAX_TEXTURE_SIZE limitation. However, the dimension that represents the number of array levels is limited by GL_MAX_ARRAY_TEXTURE_LAYERS, which is generally much smaller. OpenGL 4.5 requires that the limit be at least 2048, while OpenGL 3.3 requires it be at least 256.

Warcraft III supports 16 ground tiles that can have 32 variations each for a total of 512 for all the different ground components, assuming no special ones. For this technique to be used one should check if GL_MAX_ARRAY_TEXTURE_LAYERS supports at least the required value, and if not then either use an alternative approach (default to WC3 like logic?) or gracefully shut down the application with an message informing the user his GPU does not support the required features.

**Comment by Karaulov** [comment]
Yes , my GPU: GL_MAX_ARRAY_TEXTURE_LAYERS : 512 

"The value indicates the maximum number of layers allowed in an array texture, and must be at least 256"

**Comment by Karaulov** [comment]
You need to change terrain drawing logic (using shaders, etc), or 3.3 opengl will no longer be supported.

**Comment by stijnherfst** [comment]
What you could do is instead of having 1 giant 2d texture array for all tiles you could have a 2d texture array per tile type. Since a tile only has 32 64x64 sub textures this should fit nicely. Btw, I made you collaborator so you can push to the OpenGL 3.3 branch. There is an open pull request I did for the newest version.

**Comment by Karaulov** [comment]
Still, I hope someday support for Opengl 3.3 will be added :(

**Comment by stijnherfst** [comment]
A future redesign might change the way terrain rendering works and might enable OpenGL 3.3 support again.
