### ISSUE TITLE
Generate minimap image from .w3e/.doo files

### ISSUE THREAD

**Issue by sethmachine** [stijnherfst/HiveWE#2]
Replicate Blizzard's algorithm for generating the minimap image based on the terrain/doodad data (.w3e and .doo files).  Provide ability to create a PNG/JPEG from minimap image.

**Comment by BogdanW3** [comment]
I know this is an old issue, but I have begun working on a minimap generator, although it currently creates .tga files which can only be used for war3mapPreview.tga.  [It can be found here](https://github.com/BogdanW3/HiveWE/tree/GenMiniMapBeta) Also, I don't yet know what colors are used for corresponding ground texture ids.

**Comment by stijnherfst** [comment]
Great to have you working on the minimap image and preview! A good guess for the colors could be the 1x1 mipmap of the ground textures. You can also use the library SOIL to write TGA images. SOIL_save_image("path", SOIL_SAVE_TYPE_PNG, width, height, data_pointer); from the top of my head.

**Comment by stijnherfst** [comment]
A bit of a late update, but from version 0.5 onwards HiveWE has a working minimap. It's currently broken due to the Reforged release, but I will make sure to fix it.

**Comment by stijnherfst** [comment]
Fixed in 0.7
