### ISSUE TITLE
startup crash no libEGL

### ISSUE THREAD

**Issue by FlorianWege** [stijnherfst/HiveWE#3]
Failed to load libEGL (Das angegebene Modul wurde nicht gefunden.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (Das angegebene Modul wurde nicht gefunden.)
Failed to load and resolve WGL/OpenGL functions
Failed to load libEGL (Das angegebene Modul wurde nicht gefunden.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (Das angegebene Modul wurde nicht gefunden.)
Failed to load and resolve WGL/OpenGL functions
QOpenGLWidget: Failed to create context
Failed to load libEGL (Das angegebene Modul wurde nicht gefunden.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (Das angegebene Modul wurde nicht gefunden.)
Failed to load and resolve WGL/OpenGL functions
QOpenGLWidget: Failed to create context
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed

**Comment by flowtsohg** [comment]
Are you running in a virtual machine? Whatever's the case, the graphics drivers are not updated, or your hardware is too old. What is your DirectX/OpenGL supported version?

**Comment by FlorianWege** [comment]
Not a VM. Obviously it is a requirement issue. DX11/openGL 1.1. Just saying there should still be checks instead of a crash.

**Comment by stijnherfst** [comment]
Yes HiveWE requires OpenGL 4.5. I will look into building checks.
