### ISSUE TITLE
Add CMake support

### ISSUE THREAD

**Issue by tdauth** [stijnherfst/HiveWE#32]
Great project but I would like to build it with CMake.
I don't think the project files for specific IDEs should be part of the repo.
Most of the dependencies have CMake modules.
For others you could use "find_library".

CMake Hunter is another popular project which allows cross platform builds with CMake:
https://github.com/ruslo/hunter

**Comment by stijnherfst** [comment]
This will be a focus for the 0.6 release.

**Comment by stijnherfst** [comment]
CMake support is now live (for about a month already actually)
