### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by BananaAcid** [stijnherfst/HiveWE#37]
Frequently compile the current state and make it available (releases). Maybe even with travis-ci.org

This would greatly improve access.

**Comment by stijnherfst** [comment]
I don't really guarantee that any commit provides a stable editing environment (not even alpha like). It might still be a good idea though if I need some people to test features. I'll look into it after the 0.7 release.

**Comment by BananaAcid** [comment]
Yes, easier testing and creating some reach would attract more testers/pullrequests
