### ISSUE TITLE
Add code support for editing object data 

### ISSUE THREAD

**Issue by yxq1122** [stijnherfst/HiveWE#38]
Please add a support to completely add/edit/delete object data by codes. For example, in world editor or HiveWE, one create an ability by copying the existing one, edit some data items, and then add it to a hero. If these operations can be accomplished by writing codes, this could be great. 
To realize this functionality, the editor can give some commands to compile like what Grimex does in JNGP.

**Comment by yxq1122** [comment]
Additionally, a fileimporter is also necessary, since the dependences of objects could also be imported by codes/commands. 
Every thing to be compiled by codes would be a great feature of HiveWE for map makers.

**Comment by stijnherfst** [comment]
Maybe in the future, but not a priority at the moment. There are some [community ](https://www.hiveworkshop.com/threads/w3x-tools.324990/) written tools for it though.
