### ISSUE TITLE
startup file dialog cannot be canceled

### ISSUE THREAD

**Issue by FlorianWege** [stijnherfst/HiveWE#4]
On startup it asks for w3 main directory and you cannot cancel that process. As a user, what if I have no w3 in the first place? Also that can be extracted from registry on Windows (just make it default) and the file dialog does not save the last selection.

**Comment by stijnherfst** [comment]
The editor really only needs the game mpqs to work, but I cannot distribute these for legal reasons. I will work on the editor remembering the last selected location.

**Comment by FlorianWege** [comment]
Sure but as a user, you should still be able to close the dialog/exit the program in a normal fashion. And you can simply hardcode the registry path to look it up for convenience. Do not force it but offer it as an option. The user may want to choose another instance of the game files and of course it's different on other operating systems.

**Comment by stijnherfst** [comment]
Ah I see what you mean with cancelling the process. I will make sure that the cancel button works as you would expect.
