### ISSUE TITLE
Does not go further than choosing warcraft directory

### ISSUE THREAD

**Issue by SurDno** [stijnherfst/HiveWE#44]
Yeah, I choose one. It's definetily Warcraft directory.

![image](https://user-images.githubusercontent.com/35204405/56933447-979f3700-6af0-11e9-8b62-63a00913af14.png)

However, it still heads right back into this same menu once I pick it.

**Comment by stijnherfst** [comment]
You have to choose the Warcraft installation directory, not the Warcraft user data directory. The installation directory is usually under C:/Program FIles(x86)/Warcraft III

**Comment by SurDno** [comment]
It *is* the Warcraft installation directory. It is the place where WC3, Frozen Throne and WE exe files are located.

**Comment by stijnherfst** [comment]
Then it seems that you are not running Warcraft 1.30. The newest HiveWE only supports 1.30 or up. [Here](https://github.com/stijnherfst/HiveWE/wiki/HiveWE-doesn't-start-run-or-crashes.) you can see a table of what version of HiveWE supports what version of Warcraft.

**Comment by SurDno** [comment]
God. So no memory hacks support, right? 

Screw 1.27+. Thanks.

**Comment by SurDno** [comment]
Just saying: are there lots of internal changes between versions? Did you decide not to support older WC3 versions because of lots of compatibility issues?

**Comment by stijnherfst** [comment]
Yes  
- MPQ hierarchy structure changes between 1.28.5 and 1.29
- Game files changed to using Casc instead of MPQ in 1.30

And other small changes which altogether would end up taking a lot of time to keep on supporting instead of focusing on game versions that are more featureful.

**Comment by Flicksie** [comment]
Having this same issue on version 1.30

**Comment by BogdanW3** [comment]
> Having this same issue on version 1.30

Depending on the exact subpatch of 1.30, it's completely possible it's unsupported - during 1.30, Blizzard changed the Casc layout multiple times. Version 0.6 officially supports only 1.31
