### ISSUE TITLE
Implement cJass support

### ISSUE THREAD

**Issue by fullmetal-a** [stijnherfst/HiveWE#47]
My maps was created fully on cJass (JASS syntax is terrible)
I think may map developers prefer to use cJass instead of regular JASS.
It would be nice to implement cJass support. Without it i just cannot save my map in your editor. A hundreds of triggers written on cJass, this is impossible and have no sense to rewrite it on vJass.

By the way, cJass parser already implemented and open-source for Blizzard WE.
https://github.com/killvxk/cjass
You can make just code post-processor from this in your HiveWE.

**Comment by stijnherfst** [comment]
I looked into it a bit, but it seems like there isn't a separate preprocessor. I will add the option to call third party map script generators on map save for HiveWE 0.7 so you could then simply call a preprocessor yourself.
