### ISSUE TITLE
startup crash 'war3local.mpq'

### ISSUE THREAD

**Issue by Karaulov** [stijnherfst/HiveWE#5]
![4v5co48 1](https://user-images.githubusercontent.com/6445336/36138265-c0b22118-10a9-11e8-979e-856e0d37e949.png)

**Comment by Karaulov** [comment]
Windows 10 x64 russian

**Comment by stijnherfst** [comment]
Does your computer support OpenGL 4.5? If it does then try updating the graphics driver.

**Comment by Karaulov** [comment]
![wp2mroe 1](https://user-images.githubusercontent.com/6445336/36141623-6da5a212-10b6-11e8-9f51-4a3cc3282e14.png)
![9qppmyn 1](https://user-images.githubusercontent.com/6445336/36141640-7e61e96c-10b6-11e8-8ccc-8eaa5296abdc.png)

**Comment by Karaulov** [comment]
Possible problem in path encoding ?

**Comment by triggerhappy187** [comment]
HiveWE appears to be looking for "War3local.mpq" while you only have "War3xlocal.mpq".

**Comment by Karaulov** [comment]
How to skip this error?

**Comment by Karaulov** [comment]
I fed war3xlocal as war3local to this Editor, but I still get a crash, without War3Local.mpq error.

**Comment by DrSuperGood** [comment]
> How to skip this error? "War3local.mpq" does not exist in Warcraft III! (1.26a)

Try updating to the latest version of Warcraft III. I am pretty sure this tool is not designed to run with any other version but the latest.

**Comment by FlorianWege** [comment]
But yeah, safety checks/defensive programming pls :)

**Comment by DrSuperGood** [comment]
Well I guess it could query the version information from Game.dll or any of the Warcraft III program files. If it is earlier than 1.28.5 it then instructs the user to update their Warcraft III and closes.

**Comment by Karaulov** [comment]
I play maps with MemHack on 1.26a version and I do not plan to upgrade to new versions.

This editor will not support 1.26a and older versions?

**Comment by Karaulov** [comment]
Screenshot from DEBUG:

![t2uaulv 1](https://user-images.githubusercontent.com/6445336/36214006-48bd3a9c-11b9-11e8-8c16-3938194c64c4.png)

**Comment by Karaulov** [comment]
It looks like my video card does not support opengl 4.5 ?

**Comment by stijnherfst** [comment]
Atleast OpenGL 4.5 is required to run HiveWE. Updating your drivers might increase your OpenGL version a little bit, but probably not past version 3.0. If you have a desktop then you could buy a very cheap GPU like a Geforce GT 710.

**Comment by Karaulov** [comment]
Need buy GPU for start Warcraft III Map Editor? :(

Impossible to port code to DirectX or older version of GL?

**Comment by stijnherfst** [comment]
It's not impossible, but I use certain OpenGL 4.5 features and I'm not very keen to give those features up. The absolute lowest I could go without rewriting everything would be 3.3 so even then your hardware would be too old. Unfortunately it seems like you would need a new gpu, but there should be plenty of very cheap second hand GPUs that support OpenGL 4.5.

**Comment by Karaulov** [comment]
![dzjfdqf 1](https://user-images.githubusercontent.com/6445336/36225355-774915f8-11db-11e8-9e62-9f692f1989a2.png)

**Comment by Karaulov** [comment]
Opengl test. Video card support 3.1 opengl. 3.3 supported with latest nvidia driver.

![853ujen 1](https://user-images.githubusercontent.com/6445336/36243003-455d7408-1230-11e8-8a70-c68c52f6acef.png)

**Comment by Karaulov** [comment]
I try to port 4.5 version to 3.3, but get problem, black window.




[HiveWE-master.zip](https://github.com/stijnherfst/HiveWE/files/1726725/HiveWE-master.zip)

Please clean your repository, i found "100" copies of 'Data' and other folders )))


I use manual for port code from 4.5 to older version OpenGL.

**Comment by stijnherfst** [comment]
Yes there are some features I use that are only available on higher versions which would improve performance.

I see you changed some code to use non OpenGL DSA functions, but you forgot to change their targets to GL_TEXTURE_2D. For instance in Texture.cpp where the id in

> gl->glTexParameteri(id, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);

Should become GL_TEXTURE_2D. You forgot this too in CliffMesh.cpp, StaticMesh.cpp, PathingMap.cpp and Terrain.cpp

GL_DEBUG_OUTPUT (the function at the top of GLWidget.cpp) is an OpenGL 4.3 feature. It probably works on your machine because your GPU supports OpenGL 4.3 partially. I suggest using an  QOpenGLFunctions_3_3_Core instead of an QOpenGLExtraFunctions so you can fully target OpenGL 3.3.

You could fork HiveWE and merge in any updates I do while porting them to OpenGL 3.3. I'd be willing to suggest implementation details when you've got it up and running.

**Comment by Karaulov** [comment]
No, I can't port it to 3.3 version, I do not know how to edit shaders, etc :)  

I just see this https://github.com/Fennec-kun/Guide-to-Modern-OpenGL-Functions/blob/master/README.md 


I'll will wait until you add support 3.3 , if it happens :)


May be need using #defines for at once  add  support 3.3 and 4.5 versions, for old video cards and video cards who support 4.5 version? Or this bad ?

**Comment by stijnherfst** [comment]
It might happen at some point in the future though I'm focussing more on features at the moment. If at any time you decide to port HiveWE to OpenGL 3.3 I'd be willing to help.

**Comment by Karaulov** [comment]
Please see now :)

[HiveWE_Opengl3.zip](https://github.com/stijnherfst/HiveWE/files/1734405/HiveWE_Opengl3.zip)

But i can't convert shaders to older GL version.

**Comment by Karaulov** [comment]
**And how i can close HiveWE if i does not have Warcraft III?** 

 :D :D :D :D 

Only from task manager ? (Need select Warcraft III, but i can't close this dialog)

**Comment by Karaulov** [comment]
And i got error in Temporary\temp.mpq create, file because Temporary directory not found.

**Comment by Karaulov** [comment]
I don't know how to edit shaders, but tried to convert it to 3.3 version opengl.

[Shaders.zip](https://github.com/stijnherfst/HiveWE/files/1734645/Shaders.zip)

Compiled without errors, but possible not works. (Error while active & bind TEXTURE0 + ID )

**Comment by Karaulov** [comment]
I fix some problems, but allways got crashes at glDrawElementsInstanced function )

And now i can see WATER! )))))   And ground 1-2 seconds.

**Comment by stijnherfst** [comment]
It would be nice if you could HiveWE and then push your commits. Will be easier that way :).

**Comment by Karaulov** [comment]
I do not want to show my terrible code :) 


Okay, I'll do it.

**Comment by Karaulov** [comment]
I see new changes in code, it will take a certain time :(

Possible , you can change debug directory, and remove 'data' from HiveWE\Data ? for reduce project size? )))

`<LocalDebuggerWorkingDirectory>$(SolutionDir)$(Platform)\$(Configuration)\</LocalDebuggerWorkingDirectory>`

**Comment by stijnherfst** [comment]
Should be nothing wrong with the terrain shaders for either OpenGL 3.3 or 4.5. You havent uploaded the changes yet to the fork you did right? Because I don't see any changes. Check how big GL_MAX_ARRAY_TEXTURE_LAYERS is for you using 
`int out;
glGetIntegerv(GL_MAX_ARRAY_TEXTURE_LAYERS,&out);`

**Comment by Karaulov** [comment]
https://github.com/Karaulov/HiveWE

**Comment by Karaulov** [comment]
now problem in glUniformMatrix4fv

if replace it to 

`	GLuint MVP_loc = gl->glGetUniformLocation( ground_shader->program, "MVP" );

	gl->glUniformMatrix4fv( MVP_loc, 1, GL_FALSE, &camera.projection_view[ 0 ][ 0 ] );
`

I can see Terrain for 1-2 seconds.

**Comment by stijnherfst** [comment]
Try commenting out any rendering code in map::render() except for the terrain rendering.

**Comment by stijnherfst** [comment]
You seem to have an autoformatter change every () to ( ) (note the space) for every line of code. So I can't see in your first commit what exactly you all changed.

Also try commenting out all the lines that say "color = othercodehere" and then put "color = vec4(1, 1, 1, 1)" in terrain.fs. Then the terrain will be always white and if you continue seeing it then it means that there is a texture problem.

**Comment by Karaulov** [comment]
Problem in glUniformMatrix4fv or shaders, i don't know, but glUniformMatrix4fv wrote error <location> in all functions.  

I tried add this in terrain code:

```
GLuint MVP_loc = gl->glGetUniformLocation( ground_shader->program, "MVP" );
gl->glUniformMatrix4fv( MVP_loc, 1, GL_FALSE, &camera.projection_view[ 0 ][ 0 ] );
```

And can see 1-2 seconds terrain. But all other glUniformMatrix4fv wrote error bad <location> in debug.

**Comment by stijnherfst** [comment]
Read this about binding points. In the shader (terrain.fs) you can see layout (binding = 0). This is an OpenGL 4.2 feature. You should use "gl->glGetUniformLocation()" instead for each of these.

https://www.khronos.org/opengl/wiki/Layout_Qualifier_(GLSL)#Binding_points

**Comment by Karaulov** [comment]
color = vec4(1, 1, 1, 1) not works, now i see only water, without terrain

**Comment by Karaulov** [comment]
https://www.khronos.org/opengl/wiki/Layout_Qualifier_(GLSL)#Binding_points

Ok i will try it

**Comment by Karaulov** [comment]
I can not understand how this works. In the 330 version shaders.

**Comment by stijnherfst** [comment]
Hey, join this discord and ask for me: https://discordapp.com/invite/YpGXXNQ
Its easier talking that way.

**Comment by Karaulov** [comment]
For support 'location' in #330 version, need add this line:

**#extension GL_ARB_explicit_uniform_location : enable**

**Comment by Karaulov** [comment]
But for binding points no extension. 

![xqfzbov 1](https://user-images.githubusercontent.com/6445336/36464251-db6204e2-16df-11e8-8c8a-e8d7c607e36e.png)

**Comment by Karaulov** [comment]
**#extension GL_ARB_explicit_uniform_location : enable**
for layout location 
#extension GL_ARB_shading_language_420pack : enable
for layout binding 


Result full support 3.3 opengl : 

![amnbqut 1](https://user-images.githubusercontent.com/6445336/36466314-8e68e1fa-16ea-11e8-8e7c-12344c75aab8.png)

**Comment by stijnherfst** [comment]
I will probably have the OpenGL 3.3 as a separate branch. Use the new .gitignore in this repository and apply it to your repository so autogenerated files don't get pushed to the repo.

**Comment by Karaulov** [comment]
I updated this file. What's next?

I can just get my code and create new branch? I don't know how to do it.

**Comment by stijnherfst** [comment]
I created a new branch. After applying the gitignore you will have to select that branch as the destination of the pull request. Thank you for your work :).
