### ISSUE TITLE
Crash on export MPQ

### ISSUE THREAD

**Issue by Leandowich** [stijnherfst/HiveWE#58]
## Steps to reproduce

- Create new map with Warcraft III World Editor
- Save map
- Open map with HiveWE
- Go to file -> Export MPQ
- HiveWE crashes and no file was exported

## Issue

I can't export to MPQ as I'd like to do. When I open HiveWE, the console shows the following warning: 

![image](https://user-images.githubusercontent.com/7587685/67202748-af090e00-f409-11e9-842f-6fa259bc9875.png)

But that does not seem to cause any issue with using the program (altering terrain, pathing, testing). I have used the download link from releases for Windows (using Windows 10 x64).

**Comment by stijnherfst** [comment]
Thank you for your report! I reproduced the error and fixed it for the next build of HiveWE. With Reforged expected sometime soon I think HiveWE 0.7 will be released somewhere in December.

That specific console output can be ignored. It will not cause any problems when editing your map.
