### ISSUE TITLE
[Wiki] Update war3map.w3i documentation for 1.31

### ISSUE THREAD

**Issue by Drake53** [stijnherfst/HiveWE#59]
Link to page: https://github.com/stijnherfst/HiveWE/wiki/war3map.w3i---Map-Information

The documentation needs to be updated for the new file specification (version 28), which changed:
- version from 25 to 28;
- game version (currently 1.31.1.12164), consisting of four unsigned 32-bit ints, is inserted after the editor version;
- scripting language, which is 0 for jass and 1 for lua (32 bits int), is inserted after the water tinting color.

Additionally, I did some research of my own to find out what the three map flags introduced with format version 25 mean (though I'm not 100% sure they are correct): https://github.com/Drake53/War3Net/blob/master/src/War3Net.Build/Info/MapFlags.cs

**Comment by stijnherfst** [comment]
Thank you, I have added the changes to the specification. Also for the map flags I am pretty sure that 0x10000 is water tinting. I also added some Reforged specific info
