### ISSUE TITLE
How to download QT x64 ?

### ISSUE THREAD

**Issue by Karaulov** [stijnherfst/HiveWE#6]
https://download.qt.io/archive/qt/5.10/5.10.1/

I see only x86 version QT

**Comment by stijnherfst** [comment]
use this link: https://www.qt.io/download-qt-installer?hsCtaTracking=9f6a2170-a938-42df-a8e2-a9f0b1d6cdce%7C6cb0de4f-9bb5-4778-ab02-bfb62735f3e5

**Comment by Karaulov** [comment]
"qt-unified-windows-x86-3.0.2-online.exe"

x86, not x64

**Comment by Karaulov** [comment]
i can't download, max download speed 50 KB sec.... How to find another link to x64 qt libraries ?
