### ISSUE TITLE
HiveWE exit unexpectedly

### ISSUE THREAD

**Issue by QGB** [stijnherfst/HiveWE#63]
when i run HiveWE.exe
> D:\Games\x64-Release\HiveWE.exe
Loading CASC data from: "D:/Games/dzclient-1.8.70-full/game/Warcraft III"
 # exit

modify war3 path conf 
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\HiveWE\HiveWE]
"theme"="Light"
"warcraftDirectory"="D:/Games/dzclient-1.8.70-full/game/Warcraft III"
```

**Comment by stijnherfst** [comment]
I'm not sure what you are trying to say. Could you expand on what you are trying to say?

**Comment by QGB** [comment]
> I'm not sure what you are trying to say. Could you expand on what you are trying to say?

updated

**Comment by stijnherfst** [comment]
HiveWE does not yet support Warcraft 1.32. If you are running a lower version then you can check out [this page ](https://github.com/stijnherfst/HiveWE/wiki/HiveWE-doesn't-start-run-or-crashes.) for more information.

A new version supporting Warcraft 1.32 (Reforged) will probably come out somewhere next week.
