### ISSUE TITLE
PlayerType might be incorrect.

### ISSUE THREAD

**Issue by Ralle** [stijnherfst/HiveWE#64]
https://github.com/stijnherfst/HiveWE/blob/17f35764dadcb9aecd4ef23514f5f1c9c3916044/Base/MapInfo.h#L14

When re-implementing my player count parser I used your code as reference. From what I understand, player type 1 == human, not computer.

From what I gather 1 == human, 2 == ai. I don't know about the rest.

**Comment by BogdanW3** [comment]
https://github.com/stijnherfst/HiveWE/blob/481ae55225a15bed4cbd70e95eb517ae9eb50fd3/Base/MapInfo.cpp#L106
The number is decreased by one before converting to the enum

**Comment by Ralle** [comment]
Lol you hackers. I would prefer to make the enum match and just have 0 = Unknown or something. But that's mostly a matter of taste as long as you save the file by adding 1. Thanks for the response.
