### ISSUE TITLE
Can't start editor

### ISSUE THREAD

**Issue by kalashnikovisme** [stijnherfst/HiveWE#65]
My actions:
* click on HiveWE.exe file
* in opened window choose the directory with Warcraft 3 Frozen Throne
* window reopened and asked me to choose folder again and again...

**Comment by Skibisky** [comment]
This happened to me, when I checked [here](https://github.com/stijnherfst/HiveWE/wiki/HiveWE-doesn't-start-run-or-crashes.) I found I was using a version of Warcraft 3 too old :(

**Comment by kalashnikovisme** [comment]
@Skibisky thanks!

**Comment by Archieeeeee** [comment]
Same issue here, I'm using Warcraft 3 1.32, how to fix it

**Comment by stijnherfst** [comment]
Release 0.6 is for Warcraft 1.31 only. Release 0.7 will be for 1.32 (Reforged)

**Comment by kalashnikovisme** [comment]
@stijnherfst what version is for Warcraft 1.26?

I'm kind of old man in this case :)

**Comment by stijnherfst** [comment]
You can see a table mapping HiveWE/WC3 versions [here.](https://github.com/stijnherfst/HiveWE/wiki/HiveWE-troubleshooting)

Note that 1.26 was never officially supported by HiveWE.

**Comment by kalashnikovisme** [comment]
Thanks!
