### ISSUE TITLE
Add 1.26a support for localized games.

### ISSUE THREAD

**Issue by SurDno** [stijnherfst/HiveWE#7]
As we all know, Blizzard started updating Warcraft III recently and for a long time the latest version was 1.26a. So lots of localiziations are still working only on this version and almost all the LAN game clients (Garena, Lan Games, WARCIS) support just it. So I guess we need 1.26a support in HiveWE to make it fully replace original World Editor.

**Comment by stijnherfst** [comment]
While HiveWE probably currently works on 1.26, any support for it is on a nice to have basis. While the coming features will probably not pose any restrictions on the version requirements, a coming update might at some point.
