### ISSUE TITLE
Repeatedly prompted to select WC3 foldr

### ISSUE THREAD

**Issue by AdamBajger** [stijnherfst/HiveWE#72]
I just unsuccessfuly tried to compile my own version, and surrendered to download the 0.6 binary.
I have windows 10 and multiple version of WC3. Some on patch 1.28, and some on patch 1.32.9(latest)
After I run the executable, it asks me to select a WC3 folder, after which it asks me again as if I hadn't selected anything.
Anyone has an Idea what might be wrong? I am on windows 10.. do I need specific WC3 version? I suspect some weir infinity loop.

**Comment by stijnherfst** [comment]
Version 0.6 does not work with Reforged yet. Version 0.7 will.

**Comment by AliDeym** [comment]
I have the same issue with classical W3 TFT.

**Comment by stijnherfst** [comment]
HiveWE will not support older versions. See [here ](https://github.com/stijnherfst/HiveWE/wiki/HiveWE-troubleshooting) for a compatibility table

**Comment by xahon** [comment]
> Version 0.6 does not work with Reforged yet. Version 0.7 will.

Abandoned?

**Comment by BogdanW3** [comment]
> > Version 0.6 does not work with Reforged yet. Version 0.7 will.
> 
> Abandoned?

The code works on the latest patch, you can compile it yourself if you need the functionalities;
other than making sure it still works, I don't really have too much free time to invest, likely Eejin neither, but I can recommend HiveWE wholeheartedly as it's much faster with files, better optimized for rendering and UI-wise, and as you've almost certainly seen has a dark theme 😄

**Comment by xahon** [comment]
> > > Version 0.6 does not work with Reforged yet. Version 0.7 will.
> > 
> > 
> > Abandoned?
> 
> The code works on the latest patch, you can compile it yourself if you need the functionalities; other than making sure it still works, I don't really have too much free time to invest, likely Eejin neither, but I can recommend HiveWE wholeheartedly as it's much faster with files, better optimized for rendering and UI-wise, and as you've almost certainly seen has a dark theme 😄

I was just watching for some editor for W3 Reforged, built-in one is too unusable nowadays. May be someday I will contribute here
