### ISSUE TITLE
Unit.random should be a 3 byte vector (or a 24bit integer) when random_type == 0 

### ISSUE THREAD

**Issue by flowtsohg** [stijnherfst/HiveWE#74]
At https://github.com/stijnherfst/HiveWE/blob/master/Base/Units.cpp#L117

**Comment by stijnherfst** [comment]
Ah right. I took a look at the wc3c spec and I see that it also says the same. I presume back then I didn't care about the value as much since I haven't implemented random units/items to this day.

**Comment by flowtsohg** [comment]
The value matters less, it's more the fact the parser will fail to parse maps that use it.

**Comment by stijnherfst** [comment]
The wc3c spec says
![image](https://user-images.githubusercontent.com/8471644/103016473-5fa8fb00-4542-11eb-8269-4e02b589cb33.png)
Are there not 4 bytes for random items with random_type == 0?

**Comment by flowtsohg** [comment]
Oh it didn't register to me that you are not splitting them to two members, my mistake.

**Comment by stijnherfst** [comment]
I will at some point, but currently just needed to store the bits for saving. Thanks for pointing out a potential issue though!
