### ISSUE TITLE
Cmake compiled vs project files are all in a filter

### ISSUE THREAD

**Issue by w4454962** [stijnherfst/HiveWE#76]
The folder path is not maintained

![111111111](https://user-images.githubusercontent.com/24670862/117952486-ca1ed400-b347-11eb-85d2-343d0540cf54.png)
![2222222222](https://user-images.githubusercontent.com/24670862/117952491-cb500100-b347-11eb-9233-7550f88214c8.png)

**Comment by stijnherfst** [comment]
You should not create .SLN files from the CMakeLists, but rather directly open the HiveWE folder using either VSCode or Visual Studio. 
![image](https://user-images.githubusercontent.com/8471644/118315944-76062200-b4f6-11eb-9ef5-0bbe5f1fa312.png)
And then select the top level HiveWE folder.
