### ISSUE TITLE
Wiki: update war3map.wtg documentation

### ISSUE THREAD

**Issue by Drake53** [stijnherfst/HiveWE#82]
https://github.com/stijnherfst/HiveWE/wiki/war3map.wtg-Triggers

Categories have a property between IsComment and ParentCategoryId that is currently listed as unknown, after a little experiment I have concluded that this property should be a boolean that indicates whether the category has been collapsed (0) or expanded (1) in the trigger editor.

**Comment by BogdanW3** [comment]
It's the one thing I couldn't figure out because I never close my categories. Thank you a lot for figuring this out!

**Comment by stijnherfst** [comment]
Alright, thanks! I've updated the wiki with the new information.
