### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by thiccoder** [stijnherfst/HiveWE#85]
Hi! I`m trying to build the latest version as the binary release is severely outdated, but when I follow the build guide step-by-step an open HiveWE project in VS2022, I get this error:
CMake Error at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:816 (_find_package):
Could not find a package configuration file provided by "TBB" with any of the following names:

TBBConfig.cmake
tbb-config.cmake

Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR" to a directory containing one of the above files.  If "TBB" provides a separate development package or SDK, be sure it has been installed. C:/vcpkg/scripts/buildsystems/vcpkg.cmake	816

**Comment by stijnherfst** [comment]
Hi,
You will need to run:
`vcpkg install tbb`
And then you will progress further, but you will eventually run into other build errors that I haven't fixed yet.
If you are purely looking for a newer build of HiveWE (and not for development) then you can use this one: [HiveWE 0.7-rc.2 download](https://stack.stijnv.nl/s/9FhoRi17GYGSSuNR)

**Comment by thiccoder** [comment]
Thanks for new build, I just wanted to try new object editor. I wish i could help the project, but I dont know C++ very well, I`m more of a .NET developer.

**Comment by stijnherfst** [comment]
Fixed in newer versions as vcpkg.json mentions the dependencies
