### ISSUE TITLE
Modular separation of front and rear ends

### ISSUE THREAD

**Issue by w4454962** [stijnherfst/HiveWE#90]
The parser is separated from the renderer, divided into editor data parser, map data parser, model parser, and then combined with the front end to form hivewe. Now it is difficult to use one part separately when mixed together.

For example, it is always a bit strange to mix the code for parsing w3 * structures with the code for compiling shaders.

After modularization,  can also write data parsers of different Warcraft versions, which can improve the scalability while ensuring readability,

**Comment by stijnherfst** [comment]
While I get the general intention, do you maybe have some concrete places where you find that there is too much coupling?
