### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by DominikRicko** [stijnherfst/HiveWE#91]
In case anyone is having some issues, I've had the following:

dependency ICU not compiling because:
```
  Detected whitespace in root directory.  Please move the path to one without
  whitespaces! The required tools do not handle whitespaces correctly and the
  build will most likely fail
```
Even though vcpkg is in `C:\vcpkg\` (no whitespaces in path). The reason why it failed was because of this:
![image](https://user-images.githubusercontent.com/73482103/208238097-86782551-119d-4f60-ae1a-78bc43f8ee2b.png)
My user folder has a whitespace in it, which is why icu compilation was failing. (If someone is gonna set the build to be inside of project workspace, make sure to add `target/**` to your .gitignore file.

Next up: Outcome
If for some reason you get this problem, just do the following changes to MDX.ixx and MDLReader.cpp:
![image](https://user-images.githubusercontent.com/73482103/208238179-d3545213-adf9-47a5-b620-d7f90faec1dc.png)

Next up: c++20 Modules
If you have errors saying where some file cannot find a module that **clearly exists** within the project, switch your view to solution (which is miraculously generated at some point in time) instead of folder, try running HiveWE there, have it fail, then switch back to folder view and try running again, for some reason the modules error will be gone.

Next up:  Keyboard mappings
![image](https://user-images.githubusercontent.com/73482103/208241915-57586600-ea39-4e0c-8a81-f4c0418e9a0b.png)
So, ImGuiMouseButton_ != ImGuiKey, therefore it cannot initialize the hashmap, so I guess just remove this?

Next up: MDLWriter
![image](https://user-images.githubusercontent.com/73482103/208241980-31a13a18-29a6-47bc-bb91-12da6a4d0791.png)
Entire file has a lot of errros, but they probably stem from Timer missing?
It's an Intellisense error which I ignore.

The build error is:
![image](https://user-images.githubusercontent.com/73482103/208253211-c7c9b1bd-7833-400b-aafa-c593b13ec6b4.png)

**Comment by stijnherfst** [comment]
The build folder is now in source by default, the outcome `using` declarations were changed and the MDLReader issue has been resolved by renaming `textures` to `texturess` 🤡 . 
The issue there was that for some reason it was confusing mdx::MDX::textures with mdx::Layer::textures, but only when it was in a double lambda.
