### ISSUE TITLE
Painful build environment for Linux, doesn't work

### ISSUE THREAD

**Issue by knuxyl** [stijnherfst/HiveWE#93]
Build environment is a complete mess on Linux. Using cmake, tons of packages are not found. This could be fixed by installing the packages, however cmake isn't looking for the correct development files and is instead looking for the build environment for those libraries, in cmake.
VCPKG refuses to compile QT6 with tons of errors and having to dig around to find the correct log file, which appears to be incorrect configuration in VCPKG itself. 
Most linux distros provide these development libraries, so I think the ability to use system provided libraries over recompiling them with Microsoft tools would be best for Linux. It seems as though this should work just fine on Linux, we just need a proper build configuration.

**Comment by stijnherfst** [comment]
I would expect vcpkg to fix the Qt6 compilation quite quickly if it is broken on Linux. The reason I'm not using the system package manager, even on Linux, is that there are a ton and they are often outdated. Vcpkg solves the issue for all platforms and keeps things nice and consistent.

**Comment by knuxyl** [comment]
The problem was related to wayland, it was messing with xcb and wayland and errorred out. I didn't want to dig into it. I have all tje dev packages for both display servers, and like u said vcpkg handles that anyways. I dont know where the issue is.
